"""init schema

Revision ID: 208753ddac21
Revises: 
Create Date: 2026-07-11 21:16:11.110420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208753ddac21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=True),
    sa.Column('operation_url', sa.String(length=500), nullable=True),
    sa.Column('operation_data', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('printer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_name', sa.String(length=100), nullable=False),
    sa.Column('internal_name', sa.String(length=100), nullable=True),
    sa.Column('bambuddy_printer_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=64), server_default='P1S', nullable=False),
    sa.Column('has_ams', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='offline', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('enabled_for_auto_schedule', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_printer_bambuddy_printer_id'), ['bambuddy_printer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_printer_status'), ['status'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='customer', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('external_user_id', sa.String(length=100), nullable=True),
    sa.Column('sso_subject', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_external_user_id'), ['external_user_id'], unique=False)

    op.create_table('credit_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('available_credit', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('frozen_credit', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('currency_type', sa.String(length=20), server_default='point', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_account_user_id'), ['user_id'], unique=True)

    op.create_table('print_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='DRAFT', nullable=False),
    sa.Column('public_status', sa.String(length=32), nullable=True),
    sa.Column('material', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('layer_height', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('nozzle_size', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('estimate_weight_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimate_print_seconds', sa.Integer(), nullable=True),
    sa.Column('estimated_credit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('frozen_credit', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('actual_credit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('customer_note', sa.Text(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('public_progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_order_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_order_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_print_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_order_user_id'), ['user_id'], unique=False)

    op.create_table('bambuddy_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('bambuddy_printer_id', sa.Integer(), nullable=True),
    sa.Column('bambuddy_queue_id', sa.Integer(), nullable=True),
    sa.Column('bambuddy_archive_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('job_token', sa.String(length=128), nullable=True),
    sa.Column('bambuddy_status', sa.String(length=64), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('mapping_confidence', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['print_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bambuddy_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bambuddy_job_bambuddy_archive_id'), ['bambuddy_archive_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bambuddy_job_bambuddy_queue_id'), ['bambuddy_queue_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bambuddy_job_job_token'), ['job_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_bambuddy_job_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bambuddy_job_order_no'), ['order_no'], unique=False)

    op.create_table('credit_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('before_available', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('after_available', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('before_frozen', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('after_frozen', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['print_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_transaction_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transaction_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_credit_transaction_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transaction_user_id'), ['user_id'], unique=False)

    op.create_table('order_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('scan_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['print_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_file', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_file_order_id'), ['order_id'], unique=False)

    op.create_table('print_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('bambuddy_job_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('normalized_payload', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bambuddy_job_id'], ['bambuddy_job.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['print_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_event_bambuddy_job_id'), ['bambuddy_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_event_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_print_event_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_event_order_id'))
        batch_op.drop_index(batch_op.f('ix_print_event_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_print_event_created_at'))
        batch_op.drop_index(batch_op.f('ix_print_event_bambuddy_job_id'))

    op.drop_table('print_event')
    with op.batch_alter_table('order_file', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_file_order_id'))

    op.drop_table('order_file')
    with op.batch_alter_table('credit_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transaction_order_id'))
        batch_op.drop_index(batch_op.f('ix_credit_transaction_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_credit_transaction_created_at'))

    op.drop_table('credit_transaction')
    with op.batch_alter_table('bambuddy_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bambuddy_job_order_no'))
        batch_op.drop_index(batch_op.f('ix_bambuddy_job_order_id'))
        batch_op.drop_index(batch_op.f('ix_bambuddy_job_job_token'))
        batch_op.drop_index(batch_op.f('ix_bambuddy_job_bambuddy_queue_id'))
        batch_op.drop_index(batch_op.f('ix_bambuddy_job_bambuddy_archive_id'))

    op.drop_table('bambuddy_job')
    with op.batch_alter_table('print_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_order_user_id'))
        batch_op.drop_index(batch_op.f('ix_print_order_status'))
        batch_op.drop_index(batch_op.f('ix_print_order_order_no'))
        batch_op.drop_index(batch_op.f('ix_print_order_created_at'))

    op.drop_table('print_order')
    with op.batch_alter_table('credit_account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_account_user_id'))

    op.drop_table('credit_account')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_external_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_printer_status'))
        batch_op.drop_index(batch_op.f('ix_printer_bambuddy_printer_id'))

    op.drop_table('printer')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
