"""rename enabled_for_auto_schedule to enabled

Revision ID: fc6bc712506c
Revises: 208753ddac21
Create Date: 2026-07-11 21:24:39.703380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc6bc712506c'
down_revision = '208753ddac21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False))
        batch_op.drop_column('enabled_for_auto_schedule')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled_for_auto_schedule', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
