"""fix drift: add missing printer phase4.5 columns (source/status_detail/queue_count)

Revision ID: fef86324dcfd
Revises: fc6bc712506c
Create Date: 2026-07-12 20:45:18.635710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# down_revision 指向上游 head f5b6c7d8e9f0（本地补丁 rebase 到上游链末端，避免多 head）。
revision = 'fef86324dcfd'
down_revision = 'f5b6c7d8e9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('status_detail', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('queue_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('printer', schema=None) as batch_op:
        batch_op.drop_column('queue_count')
        batch_op.drop_column('status_detail')
        batch_op.drop_column('source')

    # ### end Alembic commands ###
